version: "3.3"

services:
  database: 
    image: mysql:8.0
    container_name: database_brokkr
    restart: always
    ports: 
      - 3307:3306 
    environment:     
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: brokkr_db           
      MYSQL_USER: brokkr_user              
      MYSQL_PASSWORD: 123456   
      MYSQL_ROOT_PASSWORD: root            
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    driver: local

networks:
  default:
    driver: bridge
